name: Sync Fork

on:
  schedule:
    - cron: '0 6/12 * * *' # Runs at 0 minutes past the hour, every 12 hours, starting at 06:00.
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: ScoopInstaller
          base: master
          head: master
